### ISSUE TITLE
Questions Regarding Equations and Terminology in paper Section 3.4 

### ISSUE THREAD

**Issue by fivezerojun** [ZxyLinkstart/HOIAnimator#2]
Hi, thanks for your excellent work, I'm looking forward to the open-source release of the code.
I have encountered a few parts of the paper that I find a bit challenging to understand, and I was hoping you could clarify them for me.

In section 3.4, for instance, in the explanation of equation (6), it mentions "j-th and k-th vertex on humans and objects," but I believe it might be more accurate to say "i-th and j-th vertex on humans and objects." Additionally, I am not quite clear on the meaning of N in the equation. Does it refer to the number of sampling points? What is its relationship with \( V_h \) and \( V_o \) in the equation?

Moreover, in equation (8), it seems that \( Q = W^K L \) might actually need to be \( W^Q L \).

Regarding ICF, my understanding is that it involves calculating the closest distance between each sampling point on the human surface and the object  surface, and similarly, the closest distance between each sampling point on the object surface and the human surface. This distance is then labeled as penetration. How does this differ from SDF?

Thank you very much for your time and assistance. I look forward to your response.

**Comment by ZxyLinkstart** [comment]
Thank you for your interest in our work:

1. Regarding the open sourcing of the code, it will take some time as the dataset and the ICF prediction code still need to be organized.
2. Concerning Equation 6, you are correct about the use of i and j; this was an oversight on our part. Thank you for your attention to detail. N refers to the number of sampling points, which can influence the overall metrics. A large number of sampling points can even lead to computational infeasibility. For Equation 8, it should indeed be K = W^K L.
3. Your understanding of ICF is correct. It involves calculating the nearest distance between each sampling point on the human surface and the object surface using the SDF calculation method. Similarly, it also calculates the nearest distance from each sampling point on the object surface to the human surface. This approach differs from the standard SDF calculation, which measures the distance of a sample point from the spatial center of either a human or an object, by using the counterpart (human or object) as the reference.

Thank you for your questions, and I hope my responses are helpful to you.

**Comment by fivezerojun** [comment]
Thank you for your patient response. Your reply helped me a lot. Thanks again.
